modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/mekanism/Mekanism/issues"
license="MIT"

[[mods]]
    modId="mekanismdefense"
    version="${version}"
    displayName="Mekanism: Defense"
    displayURL="http://aidancbrady.com/mekanism/"
    authors="Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd"
    credits="unpairedbracket, CyanideX and many others"
    logoFile="logo.png"
    description='''Defense module for Mekanism'''

[[dependencies.mekanismdefense]]
    modId="mekanism"
    mandatory=true
    versionRange="[${version}]"
    side="BOTH"